CREATE TABLE CONSUMERS 
   (	CONSUMERID NUMBER(10) NOT NULL , 
	MARKETERID NUMBER(10), 
	HANDLE VARCHAR2(40 ), 
	EMAIL VARCHAR2(40 ), 
	FIRSTNAME VARCHAR2(100 ), 
	MIDDLENAME VARCHAR2(100 ), 
	LASTNAME VARCHAR2(100 ), 
	PHONE VARCHAR2(20 ), 
	STATUS CHAR(1 ), 
	CREATEDTIME TIMESTAMP DEFAULT SYSDATE, 
	UPDATEDTIME TIMESTAMP DEFAULT SYSDATE, 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (CONSUMERID) , 
	 FOREIGN KEY (MARKETERID) REFERENCES MARKETER (MARKETERID) 
   )

  CREATE TABLE MARKETER 
   (	MARKETERID NUMBER(10) NOT NULL , 
	DOMAIN VARCHAR2(10 ), 
	MARKETERTYPE VARCHAR2(10 ), 
	NAME VARCHAR2(100 ), 
	CREATEDTIME TIMESTAMP DEFAULT SYSDATE , 
	UPDATEDTIME TIMESTAMP DEFAULT SYSDATE , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1 ) DEFAULT 'Y', 
	 PRIMARY KEY (MARKETERID)  
   )
