CREATE TABLE CONSUMER 
   (	CONSUMERID NUMBER(10) NOT NULL , 
	MARKETERID NUMBER(10), 
	HANDLE VARCHAR2(40 ), 
	EMAIL VARCHAR2(40 ), 
	FIRSTNAME VARCHAR2(100 ), 
	MIDDLENAME VARCHAR2(100 ), 
	LASTNAME VARCHAR2(100 ), 
	PHONE VARCHAR2(20 ), 
	STATUS CHAR(1 ), 
	CREATEDTIME TIMESTAMP , 
	UPDATEDTIME TIMESTAMP, 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (CONSUMERID) , 
	 FOREIGN KEY (MARKETERID) REFERENCES MARKETER (MARKETERID) 
   )

  CREATE TABLE MARKETER 
   (	MARKETERID NUMBER(10) NOT NULL , 
	DOMAIN VARCHAR2(10), 
	MARKETERTYPE VARCHAR2(10), 
	NAME VARCHAR2(100), 
	CREATEDTIME TIMESTAMP , 
	UPDATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20) DEFAULT USER NOT NULL , 
	UPDATEDBY VARCHAR2(20) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1) DEFAULT ‘Y’, 
	 PRIMARY KEY (MARKETERID)  
   )


  CREATE TABLE MARKETERPREFERREDSUPPLIER 
   (	MARKETERSUPPLIERID NUMBER(10) NOT NULL , 
	MARKETERID NUMBER(10), 
	SUPPLIERID NUMBER(10), 
	 PRIMARY KEY (MARKETERSUPPLIERID)  , 
	 FOREIGN KEY (MARKETERID)
	  REFERENCES MARKETER (MARKETERID) , 
	 FOREIGN KEY (SUPPLIERID)
	  REFERENCES SUPPLIER (SUPPLIERID) 
   )


  CREATE TABLE MARKETERPRODUCT 
   (	MARKETERPRODUCTID NUMBER(10) NOT NULL , 
	MARKETERID NUMBER(10), 
	PRODUCTID NUMBER(10), 
	SKU VARCHAR2(20 ), 
	PRICE NUMBER(8,0), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1 ), 
	 PRIMARY KEY (MARKETERPRODUCTID)  , 
	 FOREIGN KEY (MARKETERID)
	  REFERENCES MARKETER (MARKETERID) , 
	 FOREIGN KEY (PRODUCTID)
	  REFERENCES PRODUCT (PRODUCTID) 
   )


  CREATE TABLE CONSUMEROFFER 
   (	CONSUMEROFFERID NUMBER(10) NOT NULL , 
	CONSUMERID NUMBER(10), 
	OFFERSTATUSID NUMBER(10), 
	MARKETERPRODUCTID NUMBER(10), 
	OFFERREDDATE TIMESTAMP , 
	QUANTITY NUMBER(10,0), 
	MAXPRICE NUMBER(8,0), 
	ENDDATE TIMESTAMP , 
	ISCURRENT CHAR(1 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (CONSUMEROFFERID)  , 
	 FOREIGN KEY (MARKETERPRODUCTID)
	  REFERENCES MARKETERPRODUCT (MARKETERPRODUCTID) , 
	 FOREIGN KEY (CONSUMERID) REFERENCES CONSUMERS (CONSUMERID) , 
	 FOREIGN KEY (OFFERSTATUSID) REFERENCES STATUS (OFFERSTATUSID) 
   )

  CREATE TABLE ADDRESS 
   (	ADDRESSID NUMBER(10) NOT NULL , 
	ADDRESSTYPEID NUMBER(10), 
	CONSUMERID NUMBER(10), 
	LINE1 VARCHAR2(20 ), 
	LINE2 VARCHAR2(20 ), 
	LINE3 VARCHAR2(20 ), 
	CITY VARCHAR2(20 ), 
	ZIPPOSTALCODE NUMBER(5,0), 
	STATEPROVINCECOUNTY VARCHAR2(20 ), 
	COUNTRY VARCHAR2(20 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (ADDRESSID)
  
  , 
	 FOREIGN KEY (ADDRESSTYPEID)
	  REFERENCES ADDRESSTYPE (ADDRESSTYPEID) , 
	 FOREIGN KEY (CONSUMERID)
	  REFERENCES CONSUMERS (CONSUMERID) 
   )
  

  CREATE TABLE SUPPLIER 
   (	SUPPLIERID NUMBER(10) NOT NULL , 
	DOMAIN VARCHAR2(10 ), 
	SUPPLIERTYPE VARCHAR2(10 ), 
	NAME VARCHAR2(100 ), 
	PRIORITY CHAR(1 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1 ), 
	 PRIMARY KEY (SUPPLIERID)
  
  
   )



  CREATE TABLE PRODUCT 
   (	PRODUCTID NUMBER(10) NOT NULL , 
	MANUFACTURER VARCHAR2(20 ), 
	UPC VARCHAR2(20 ), 
	EAN VARCHAR2(20 ), 
	GTIN VARCHAR2(20 ), 
	NAME VARCHAR2(100 ), 
	DESCRIPTION VARCHAR2(20 ), 
	UOM VARCHAR2(10 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) NOT NULL , 
	ISACTIVE CHAR(1 ), 
	 PRIMARY KEY (PRODUCTID)
  
  
   )


  CREATE TABLE OFFERMATCH 
   (	OFFERMATCHID NUMBER(10) NOT NULL , 
	CONSUMEROFFERID NUMBER(10), 
	SUPPLIEROFFERID NUMBER(10), 
	QUANTITY NUMBER(10,0), 
	OFFERSTATUSID NUMBER(10), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (OFFERMATCHID)
  
  , 
	 FOREIGN KEY (OFFERSTATUSID)
	  REFERENCES STATUS (OFFERSTATUSID) , 
	 FOREIGN KEY (CONSUMEROFFERID)
	  REFERENCES CONSUMEROFFER (CONSUMEROFFERID) , 
	 FOREIGN KEY (SUPPLIEROFFERID)
	  REFERENCES SUPPLIEROFFER (SUPPLIEROFFERID) 
   )

  CREATE TABLE STATUS 
   (	OFFERSTATUSID NUMBER(10) NOT NULL , 
	STATUS CHAR(1 ), 
	DESCRIPTION VARCHAR2(20 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	 PRIMARY KEY (OFFERSTATUSID)
  
  
   )

CREATE TABLE ADDRESSTYPE 
   (	ADDRESSTYPEID NUMBER(10) NOT NULL , 
	NAME VARCHAR2(100 ), 
	 PRIMARY KEY (ADDRESSTYPEID)
  
  
   )


  CREATE TABLE SUPPLIERPRODUCT 
   (	SUPPLIERPRODUCTID NUMBER(10) NOT NULL , 
	SUPPLIERID NUMBER(10), 
	PRODUCTID NUMBER(10), 
	PRICE NUMBER(8,0), 
	SKU VARCHAR2(20 ), 
	PRIORITY CHAR(1 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1 ), 
	 PRIMARY KEY (SUPPLIERPRODUCTID), 
	 FOREIGN KEY (SUPPLIERID)
	  REFERENCES SUPPLIER (SUPPLIERID) , 
	 FOREIGN KEY (PRODUCTID)
	  REFERENCES PRODUCT (PRODUCTID) 
   )


CREATE TABLE SUPPLIERPRODUCT 
   (	SUPPLIERPRODUCTID NUMBER(10) NOT NULL , 
	SUPPLIERID NUMBER(10), 
	PRODUCTID NUMBER(10), 
	PRICE NUMBER(8,0), 
	SKU VARCHAR2(20 ), 
	PRIORITY CHAR(1 ), 
	CREATEDTIME TIMESTAMP , 
	CREATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	UPDATEDTIME TIMESTAMP , 
	UPDATEDBY VARCHAR2(20 ) DEFAULT USER NOT NULL , 
	ISACTIVE CHAR(1 ), 
	 PRIMARY KEY (SUPPLIERPRODUCTID), 
	 FOREIGN KEY (SUPPLIERID)
	  REFERENCES SUPPLIER (SUPPLIERID) , 
	 FOREIGN KEY (PRODUCTID)
	  REFERENCES PRODUCT (PRODUCTID) 
   )




